[[pages]]
path = "streamlit_app.py"
name = "Interrogate Observatory"
icon = ":house:"

[[pages]]
path = "pages/creer_observatoire.py"
name = "Create Observatory"
icon = ":books:"

[[pages]]
path = "pages/nouvel_observatoire.py"
name = "New Observatory"
icon = ":bar_chart:"
